### ISSUE TITLE
Add support for .NET Framework

### ISSUE THREAD

**Issue by ezekielnewren** [dahomey-technologies/Dahomey.Cbor#82]
I can almost get your code to work in a .NET Framework project, but when I load keepass it complains that.

System.IO.FileLoadException: Could not load file or assembly '**System.Buffers, Version=4.0.2.0**, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Dahomey.Cbor.Util.ByteBufferWriter.CheckAndResizeBuffer(Int32 sizeHint)
   at Dahomey.Cbor.Util.ByteBufferWriter.GetSpan(Int32 sizeHint)
   at Dahomey.Cbor.Serialization.CborWriter.WriteRawByte(Byte b)
   at Dahomey.Cbor.Serialization.CborWriter.WriteHeader(CborMajorType majorType, Byte additionalValue)
   at Dahomey.Cbor.Serialization.CborWriter.WriteInteger(CborMajorType majorType, UInt64 value)
   at Dahomey.Cbor.Serialization.CborWriter.WriteSize(CborMajorType majorType, Int32 size)
   at Dahomey.Cbor.Serialization.CborWriter.WriteBeginMap(Int32 size)
   at Dahomey.Cbor.Serialization.CborWriter.WriteMap[TC](ICborMapWriter`1 mapWriter, TC& context)
   at Dahomey.Cbor.Serialization.Converters.ObjectConverter`1.Write(CborWriter& writer, T value, LengthMode lengthMode)
   at Dahomey.Cbor.Serialization.Converters.CborConverterBase`1.Write(CborWriter& writer, T value)
   at Dahomey.Cbor.Cbor.Serialize[T](T input, IBufferWriter`1& buffer, CborOptions options)
   at KeePassKeyring.Util.SerializeObject[T](T obj)
   at KeePassKeyring.Util.WriteObject[T](Stream stream, T obj)
   at KeePassKeyring.KeePassKeyringExt.Initialize(IPluginHost _host) in C:\Users\vmuser\RiderProjects\kpkr\KeePassKeyring\Plugin.cs:line 73
   at KeePass.Plugins.PluginManager.LoadPlugins(List`1 lFiles, String strTypeName, String strDisplayFilePath, Boolean bSkipCacheFiles)

I cannot for the life of me get the System.Buffers to play nicely.

**Comment by mcatanzariti** [comment]
tested with Dahomey.Cbor 1.17.0 & .Net Framework 4.7.2

```csharp
using Dahomey.Cbor;
using System.IO;
using System.Threading.Tasks;

namespace CborNetFrameworkTest
{
    class MyObject
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    internal class Program
    {
        static async Task Main(string[] args)
        {
            MyObject myObject = new MyObject
            {
                Id = 1,
                Name = "foo"
            };

            MemoryStream stream = new MemoryStream();

            await Cbor.SerializeAsync(myObject, stream);

            stream.Position = 0;
            MyObject myObject2 = await Cbor.DeserializeAsync<MyObject>(stream);
        }
    }
}
```
