### ISSUE TITLE
Support record classes

### ISSUE THREAD

**Issue by robertvazan** [dahomey-technologies/Dahomey.Cbor#88]
Please add support for record classes, for example:

```csharp
record Spaceship(int Passegers, double Fuel) { }
```

Right now I just get an exception:

```
CborException: Cannot find a default constructor on type
```

**Comment by robertvazan** [comment]
If I disable my custom object mapping and rely on defaults, I get strange exception:

```
 ---> System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String s)
   at Dahomey.Cbor.Serialization.Converters.MemberConverter`2..ctor(CborConverterRegistry registry, IMemberMapping memberMapping)
 ```

As if there's a member with null name.

**Comment by robertvazan** [comment]
I think the problem is caused by compiler-generated property `protected virtual Type EqualityContract` that is present in all record classes. The following mapping convention seems to work for my record classes:

```csharp
class RecordConvention : IObjectMappingConvention
{
    public void Apply<T>(SerializationRegistry registry, ObjectMapping<T> mapping)
    {
        // Assume there is only one constructor that initializes all record properties.
        var constructor = mapping.ObjectType.GetConstructors()[0];
        mapping.MapCreator(constructor);
        // Serialize only public properties that are also constructor parameters.
        foreach (var property in mapping.ObjectType.GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly))
            if (constructor.GetParameters().Any(parameter => parameter.Name == property.Name))
                mapping.MapMember(property, property.PropertyType);
    }
}
```
